### ISSUE TITLE
Unknown named curve: 1.2.156.10197.1.301  错误

### ISSUE THREAD

**Issue by wemem** [commis/fabric-sdk-java-gm#1]
我这边用fabric 1.4.3版本改的国密搭建了一个区块链网络，然后我用此项目的sdk调用出现下面错误，
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=57309:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/tools.jar:/Users/simkit/work/fabric-sdk-java-example/target/classes:/Users/simkit/.m2/repository/com/ufscs/fabric-sdk-java/fabric-sdk-java/1.4.6/fabric-sdk-java-1.4.6.jar:/Users/simkit/.m2/repository/io/grpc/grpc-netty/1.23.0/grpc-netty-1.23.0.jar:/Users/simkit/.m2/repository/io/grpc/grpc-core/1.23.0/grpc-core-1.23.0.jar:/Users/simkit/.m2/repository/com/google/android/annotations/4.1.1.4/annotations-4.1.1.4.jar:/Users/simkit/.m2/repository/io/perfmark/perfmark-api/0.17.0/perfmark-api-0.17.0.jar:/Users/simkit/.m2/repository/io/opencensus/opencensus-api/0.21.0/opencensus-api-0.21.0.jar:/Users/simkit/.m2/repository/io/opencensus/opencensus-contrib-grpc-metrics/0.21.0/opencensus-contrib-grpc-metrics-0.21.0.jar:/Users/simkit/.m2/repository/io/netty/netty-codec-http2/4.1.38.Final/netty-codec-http2-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-common/4.1.38.Final/netty-common-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-buffer/4.1.38.Final/netty-buffer-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-transport/4.1.38.Final/netty-transport-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-resolver/4.1.38.Final/netty-resolver-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-codec/4.1.38.Final/netty-codec-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-handler/4.1.38.Final/netty-handler-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-codec-http/4.1.38.Final/netty-codec-http-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-handler-proxy/4.1.38.Final/netty-handler-proxy-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/netty/netty-codec-socks/4.1.38.Final/netty-codec-socks-4.1.38.Final.jar:/Users/simkit/.m2/repository/io/grpc/grpc-protobuf/1.23.0/grpc-protobuf-1.23.0.jar:/Users/simkit/.m2/repository/io/grpc/grpc-api/1.23.0/grpc-api-1.23.0.jar:/Users/simkit/.m2/repository/io/grpc/grpc-context/1.23.0/grpc-context-1.23.0.jar:/Users/simkit/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/simkit/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/Users/simkit/.m2/repository/com/google/guava/guava/26.0-android/guava-26.0-android.jar:/Users/simkit/.m2/repository/org/checkerframework/checker-compat-qual/2.5.2/checker-compat-qual-2.5.2.jar:/Users/simkit/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/simkit/.m2/repository/com/google/api/grpc/proto-google-common-protos/1.12.0/proto-google-common-protos-1.12.0.jar:/Users/simkit/.m2/repository/io/grpc/grpc-protobuf-lite/1.23.0/grpc-protobuf-lite-1.23.0.jar:/Users/simkit/.m2/repository/io/grpc/grpc-stub/1.23.0/grpc-stub-1.23.0.jar:/Users/simkit/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.26.Final/netty-tcnative-boringssl-static-2.0.26.Final.jar:/Users/simkit/.m2/repository/com/google/protobuf/protobuf-java/3.10.0/protobuf-java-3.10.0.jar:/Users/simkit/.m2/repository/com/google/protobuf/protobuf-java-util/3.10.0/protobuf-java-util-3.10.0.jar:/Users/simkit/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar:/Users/simkit/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/simkit/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.62/bcpkix-jdk15on-1.62.jar:/Users/simkit/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.62/bcprov-jdk15on-1.62.jar:/Users/simkit/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/simkit/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar:/Users/simkit/.m2/repository/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar:/Users/simkit/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar:/Users/simkit/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/simkit/.m2/repository/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar:/Users/simkit/.m2/repository/org/apache/httpcomponents/httpclient/4.5.10/httpclient-4.5.10.jar:/Users/simkit/.m2/repository/org/apache/httpcomponents/httpcore/4.4.12/httpcore-4.4.12.jar:/Users/simkit/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar:/Users/simkit/.m2/repository/org/glassfish/javax.json/1.1.4/javax.json-1.1.4.jar:/Users/simkit/.m2/repository/org/yaml/snakeyaml/1.25/snakeyaml-1.25.jar:/Users/simkit/.m2/repository/org/miracl/milagro/amcl/milagro-crypto-java/0.4.0/milagro-crypto-java-0.4.0.jar:/Users/simkit/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar:/Users/simkit/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar:/Users/simkit/.m2/repository/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar:/Users/simkit/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar main.java.Main
15:11:08,269 INFO  - main.java.Main                    - 开始加载配置文件
15:11:09,479 ERROR - org.hyperledger.fabric.sdk.Endpoint - Endpoint grpcs://localhost:7051, exception 'Input stream does not contain valid certificates.'
java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:205)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:279)
	at org.hyperledger.fabric.sdk.Endpoint.createEndpoint(Endpoint.java:511)
	at org.hyperledger.fabric.sdk.Peer.getEndorserClient(Peer.java:249)
	at org.hyperledger.fabric.sdk.Peer.sendProposalAsync(Peer.java:232)
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4481)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:958)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:924)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:2051)
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1888)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1273)
	at main.java.FabricNetwork.getChannel(FabricNetwork.java:115)
	at main.java.Main.main(Main.java:47)
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1190)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1179)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:203)
	... 12 more
Caused by: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.ec.ECParameters.engineInit(ECParameters.java:143)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	... 19 more
15:11:09,484 ERROR - org.hyperledger.fabric.sdk.Channel - Channel Channel{id: 1, name: mychannel} sending proposal with transaction: 95d62ddf304ee111695eb399838d679462c32e359b1b84300c757b3f89d6eb1b to Peer{ id: 7, name: peer0.org1.example.com, channelName: mychannel, url: grpcs://localhost:7051, mspid: Org1MSP} failed because of: Input stream does not contain valid certificates.
java.lang.Exception: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4531)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:958)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:924)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:2051)
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1888)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1273)
	at main.java.FabricNetwork.getChannel(FabricNetwork.java:115)
	at main.java.Main.main(Main.java:47)
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:205)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:279)
	at org.hyperledger.fabric.sdk.Endpoint.createEndpoint(Endpoint.java:511)
	at org.hyperledger.fabric.sdk.Peer.getEndorserClient(Peer.java:249)
	at org.hyperledger.fabric.sdk.Peer.sendProposalAsync(Peer.java:232)
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4481)
	... 7 more
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1190)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1179)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:203)
	... 12 more
Caused by: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.ec.ECParameters.engineInit(ECParameters.java:143)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	... 19 more
15:11:09,486 ERROR - org.hyperledger.fabric.sdk.Channel - getConfigBlock for channel mychannel failed with peer peer0.org1.example.com.  Status FAILURE, details: Channel Channel{id: 1, name: mychannel} sending proposal with transaction: 95d62ddf304ee111695eb399838d679462c32e359b1b84300c757b3f89d6eb1b to Peer{ id: 7, name: peer0.org1.example.com, channelName: mychannel, url: grpcs://localhost:7051, mspid: Org1MSP} failed because of: Input stream does not contain valid certificates.
org.hyperledger.fabric.sdk.exception.ProposalException: getConfigBlock for channel mychannel failed with peer peer0.org1.example.com.  Status FAILURE, details: Channel Channel{id: 1, name: mychannel} sending proposal with transaction: 95d62ddf304ee111695eb399838d679462c32e359b1b84300c757b3f89d6eb1b to Peer{ id: 7, name: peer0.org1.example.com, channelName: mychannel, url: grpcs://localhost:7051, mspid: Org1MSP} failed because of: Input stream does not contain valid certificates.
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:969)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:924)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:2051)
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1888)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1273)
	at main.java.FabricNetwork.getChannel(FabricNetwork.java:115)
	at main.java.Main.main(Main.java:47)
15:11:09,493 ERROR - org.hyperledger.fabric.sdk.Endpoint - Endpoint grpcs://localhost:7051, exception 'Input stream does not contain valid certificates.'
java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:205)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:279)
	at org.hyperledger.fabric.sdk.Endpoint.createEndpoint(Endpoint.java:511)
	at org.hyperledger.fabric.sdk.Peer.initiateEventing(Peer.java:145)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1298)
	at main.java.FabricNetwork.getChannel(FabricNetwork.java:115)
	at main.java.Main.main(Main.java:47)
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1190)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1179)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:203)
	... 6 more
Caused by: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.ec.ECParameters.engineInit(ECParameters.java:143)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	... 13 more
15:11:09,493 ERROR - org.hyperledger.fabric.sdk.Channel - java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
org.hyperledger.fabric.sdk.exception.TransactionException: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1325)
	at main.java.FabricNetwork.getChannel(FabricNetwork.java:115)
	at main.java.Main.main(Main.java:47)
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:205)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:279)
	at org.hyperledger.fabric.sdk.Endpoint.createEndpoint(Endpoint.java:511)
	at org.hyperledger.fabric.sdk.Peer.initiateEventing(Peer.java:145)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1298)
	... 2 more
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1190)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1179)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:203)
	... 6 more
Caused by: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.ec.ECParameters.engineInit(ECParameters.java:143)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	... 13 more
15:11:09,494 ERROR - main.java.Main                    - exception
org.hyperledger.fabric.sdk.exception.TransactionException: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1325)
	at main.java.FabricNetwork.getChannel(FabricNetwork.java:115)
	at main.java.Main.main(Main.java:47)
Caused by: java.lang.IllegalArgumentException: Input stream does not contain valid certificates.
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:205)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:279)
	at org.hyperledger.fabric.sdk.Endpoint.createEndpoint(Endpoint.java:511)
	at org.hyperledger.fabric.sdk.Peer.initiateEventing(Peer.java:145)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1298)
	... 2 more
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1804)
	at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:195)
	at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:102)
	at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
	at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:1190)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1179)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:203)
	... 6 more
Caused by: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
	at sun.security.ec.ECParameters.engineInit(ECParameters.java:143)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at sun.security.x509.X509Key.parse(X509Key.java:168)
	at sun.security.x509.CertificateX509Key.<init>(CertificateX509Key.java:75)
	at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:667)
	at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:167)
	... 13 more

Process finished with exit code 0

```
netty 里面的ssl链接是不是不支持国密算法？

**Comment by a1753630314** [comment]
@wemem 我这里也遇到了这个问题，应该是ssl国密不支持，不知道你那里解决了没有？？

**Comment by commis** [comment]
还没有解决，要修改会比较麻烦，需要动底层的jar包。发自我的华为手机-------- 原始邮件 --------发件人： a1753630314 <notifications@github.com>日期： 2020年4月26日周日 10:16收件人： commis/fabric-sdk-java-gm <fabric-sdk-java-gm@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [commis/fabric-sdk-java-gm] Unknown named curve: 1.2.156.10197.1.301  错误 (#1)

@wemem 我这里也遇到了这个问题，应该是ssl国密不支持，不知道你那里解决了没有？？

**Comment by bhtdz-zhou** [comment]
> 还没有解决，要修改会比较麻烦，需要动底层的jar包。发自我的华为手机-------- 原始邮件 --------发件人： a1753630314 <notifications@github.com>日期： 2020年4月26日周日 10:16收件人： commis/fabric-sdk-java-gm <fabric-sdk-java-gm@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： Re: [commis/fabric-sdk-java-gm] Unknown named curve: 1.2.156.10197.1.301 错误 (#1) @wemem 我这里也遇到了这个问题，应该是ssl国密不支持，不知道你那里解决了没有？？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

麻烦问一下作者是否有计划支持国密版本的ssl呢
